name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Define the explicit user to bypass the "chown invalid user" bug in the docker action
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        env:
          USER: root
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
